version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: '../../backend'
    volumes:
      - /app/node_modules
      - ../../backend:/app

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: '../../client'
    volumes:
        - /app/node_modules
        - ../../client:/app  